export const FETCH_USERS = "FETCH_USERS";
export const FETCH_POSTS = "FETCH_POSTS";
export const DELETE_USER = "DELETE_USER";
export const POST_LOADING_START = "POST_LOADING_START";
export const USER_LOADING_START = "USER_LOADING_START";

export const HANDLE_POST_TITLE_CHANGE = "HANDLE_POST_TITLE";
export const HANDLE_POST_BODY_CHANGE = "HANDLE_POST_BODY";

export const HANDLE_POST_TITLE_BLUR = "HANDLE_POST_TITLE_BLUR";
export const HANDLE_POST_BODY_BLUR = "HANDLE_POST_BODY_BLUR";

export const HANDLE_POST_SUBMIT = "HANDLE_POST_SUBMIT";
export const POST_CREATE_LOADING_START = "POST_CREATE_LOADING_START";
export const POST_CREATE_SHOW_MESSAGE = "POST_CREATE_SHOW_MESSAGE";
export const POST_CREATE_HIDE_MESSAGE = "POST_CREATE_HIDE_MESSAGE";