export const FETCH_USERS = "FETCH_USERS";
export const FETCH_POSTS = "FETCH_POSTS";
export const DELETE_USER = "DELETE_USER";
export const POST_LOADING_START = "POST_LOADING_START";
export const USER_LOADING_START = "USER_LOADING_START";